% MaxNumSplits = 10,15,25
MaxNumSplits = 25;
[W0,b0,W1,b1,W2,b2,tree,error_check,NumSplits] = ...
    initAllWb(XTrain,yTrain,MaxNumSplits);

disp('tree training rmse:')
sqrt(mean((predict(tree, XTrain) - yTrain).^2))

disp('tree testing rmse:')
sqrt(mean((predict(tree, XTest) - yTest).^2))

miniBatchSize = 10000;
maxEps = 20;

ndtOptions = trainingOptions('sgdm', ...
    'miniBatchSize', miniBatchSize, ...
    'Momentum',0.1, ...
    'MaxEpochs',maxEps, ...
    'ValidationData', {XTest, yTest}, ...
    'ValidationFrequency',floor(size(XTrain,1)/miniBatchSize), ...
    'InitialLearnRate',1e-1, ...
    'Verbose',true, ...
    'Plots','training-progress');

% ndtOptions = trainingOptions('adam', ...
%     'GradientDecayFactor',0.9, ...
%     'SquaredGradientDecayFactor',0.9, ...
%     'miniBatchSize', miniBatchSize, ...
%     'MaxEpochs',100, ...
%     'ValidationData', {XTest, yTest}, ...
%     'ValidationFrequency',floor(size(XTrain,1)/miniBatchSize), ...
%     'InitialLearnRate',1e-2, ...
%     'Verbose',true, ...
%     'Plots','training-progress');

fc1 = fullyConnectedLayer(NumSplits);
fc1.Weights = W0;
fc1.Bias = b0;
fc2 = fullyConnectedLayer(NumSplits+1);
fc2.Weights = W1;
fc2.Bias = b1;
fc3 = fullyConnectedLayer(1);
fc3.Weights = W2;
fc3.Bias = b2;

ndtLayers = [featureInputLayer(size(XTrain,2)),...
    fc1, reluLayer,...
    fc2, sigmoidLayer,...
    fc3, regressionLayer];



[ndt, ndtInfo] = trainNetwork(XTrain,yTrain,ndtLayers,ndtOptions);

% fig = findall(groot,'Type','Figure');
% saveas(fig, fullfile(dir, 'figures', 'ndtTrainTest_lr_1e-1'));
% names = sprintf('ndt_40eps_lr_1e-1.mat');
% save(fullfile(dir, 'results', names), 'ndt', 'ndtInfo')




